### ISSUE TITLE
Further subdivide the digitizer into electronics and DAQ.

### ISSUE THREAD

**Issue by cwwalter** [WCSim/WCSim#11]
This depends on issue #4 being resolved.  But, after that work is done the current digitizer can be further sub-divided in electronics and DAQ pieces.  This way one could implement things like the current SK software triggers cleanly.

**Comment by eosullivan** [comment]
I think this plan looks good in principle. Extending this idea of deriving from a base class to include the digitizer and trigger/DAQ is certainly where we want to go with this. For the actual details of how the electronics will be set up in the code, this would probably benefit from having an SK electronics expert look over it. In the meeting last night, Chris suggested that an SK electronics expert could perhaps come and give a talk at the HK software meeting to refresh us on the details of how the new digitization scheme works.

**Comment by eosullivan** [comment]
It looks like I can only assign one person to this, but this will also be the responsibility of @dewhurst, and @stewartt1982. Once the code is split up into the digitizer and the DAQ, @thomaslindner can make the digitizer more modular and can add in the FADC.
