### ISSUE TITLE
Make the NDigits2 trigger option stable

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#114]
This is a nice example of how to add new derived trigger classes into WCSimWCTrigger.cc, and is a good example of using multiple triggers. However, this experimental feature occasionally throws the error: 

``WCSim: src/WCSimWCTrigger.cc:371: void WCSimWCTriggerBase::FillDigitsCollection(WCSimWCDigitsCollection*, bool, TriggerType_t): Assertion `triggered_composition.size()' failed.
``
This trigger class must be stable before the next release of WCSim. I will nominally assign @tdealtry, but if there is someone else who is more appropriate, please let me know.

**Comment by tdealtry** [comment]
#118 fixes the most obvious causes of this. I'll set some high stats jobs running at various energies to check if there are any remaining issues.

**Comment by tdealtry** [comment]
I've run some high/medium/low energy electron particle guns with 5000 events in each. No crashes were seen, and distributions look fine. So I'm fairly confident that #118 fixes everything.

**Comment by tdealtry** [comment]
I think we can close this issue now. The error that was first reported has now been fixed; another issue can be made if there are any future problems.

**Comment by eosullivan** [comment]
Ah, GitHub was doing so well with automatically closing issues. I'll close this now.
