### ISSUE TITLE
Add HPDs to the list of possible tubes.

### ISSUE THREAD

**Issue by cwwalter** [WCSim/WCSim#12]
After #4 is finalized by @eosullivan then the work from @YujiOkajima can also be incorporated to add the HPDs.  This needs to be done in a way that is accessible to both SK and HK and involves adding the new single PE distribution etc.  It should be handled like the other tube cases and not with hardcoded 'if' statements.

**Comment by eosullivan** [comment]
This issue was closed by pull request #34.
