### ISSUE TITLE
Make the NDigits and total p.e. distributions at high energy in the new digitizer/trigger scheme agree with the old digitizer/trigger

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#120]
The combination of the new SKI digitizer and NDigits trigger disagrees with the old WCSim SKI_SKDETSIM combined digitizer+trigger in the NDigits and total p.e. distributions for high energy electron particle guns. In the past, the WCSim SKI_SKDETSIM was compared* with the SKI mode of skdetsim, and good agreement was seen at high energy. Therefore it is important for WCSim's new classes to agree with the old class, in order to perform high energy physics studies.
*@cwwalter it'd be useful to know which configurations were tested (e.g. particle gun particle types, energies, etc.), which distributions were plotted, and how close the agreement was. Could you post a link to slides/documents?

![nhits-1](https://cloud.githubusercontent.com/assets/11757479/10365733/66901a28-6dbd-11e5-8996-76da187c22f3.png)
NDigits is calculated as the number of digitized hits in the first subevent in the output file, and so is after the entire digitization + trigger process.
![pe-1](https://cloud.githubusercontent.com/assets/11757479/10365734/66ad57fa-6dbd-11e5-83cf-9b72da4028cf.png)
Total p.e. is calculated by summing Q of the digitized hits in the first subevent in the output file.

The above plots are for 5 GeV electrons without dark noise. See #89 [verification plots](https://gist.github.com/tdealtry/0efb539cd2ab425900e8) for more configurations.

It is useful to explain how digits are created & saved
* New code
  1. Find the first raw hit on a PMT in the simulation. Integrate hits on this PMT for hit time + 200 ns.
  2. Apply the efficiency factor & threshold function. Create a new digit if threshold is passed
  3. Reject hits in the deadtime window (0 ns)
  4. Find the next hit. Integrate for hit time + 200 ns. Go to iv.
  5. Only digits that pass an NDigit trigger are saved
* Old code
  1. Trigger on raw hits
  1. Find the first raw hit on a PMT in the subevent window. Integrate hits on this PMT for hit time + 200 ns.
  2. Apply the efficiency factor & threshold function. Create a new digit if threshold is passed
  3. Digitizer is now dead until next subevent window
  3. All digits created are saved
  

The expected cause of this is the number of digits (digitized hits) allowed per PMT per subevent window - in the old code it is 0 or 1, whereas in the new code >1 is allowed.

There are a few potential solutions
* Restrict the new code so that it allows only only 0 or 1 digit per PMT per subevent window.
* Change the digitizer deadtime in the new code ([verification plots appendix A](https://gist.github.com/tdealtry/0efb539cd2ab425900e8) shows that moving from 0 ns to 500 ns, this works for electron guns)
* Change the digitizer integration window in the new code (#116) - a longer integration window will cause a reduction in NDigits, but not total p.e. (unless combined with digitizer deadtime)

I've tried having a look at the skdetsim code to see what values are used, and how many digits per PMT per subevent window are allowed, but have been unable to work this out (I can't run skdetsim, I don't have all the source files, and I don't know fortran). So it'd be useful if someone who knows skdetsim could take a look & report on how it does things, so that the best solution(s) can be found.

This should be solved before #115 is merged

**Comment by tdealtry** [comment]
I've done some tests restricting the maximum number of digits per PMT per subevent window is 1 (the first digit in time order is taken). There is good agreement between the old code and the new code with this restriction for both NDigits and average digit p.e.

![nhits-1](https://cloud.githubusercontent.com/assets/11757479/10453104/ba546eec-71a1-11e5-97cd-31a64fadde34.png)

![peperdigi-1](https://cloud.githubusercontent.com/assets/11757479/10453105/ba67a4b2-71a1-11e5-84b0-c062a8b25c4c.png)

So the next steps are:
* work out what SKDETSIM does
* get more information on what WCSim/SKDETSIM checks were done in the past

Then using this we can decide which method (restrict number of digits per PMT per subevent, change default time variables) to use to fix this bug.

**Comment by eosullivan** [comment]
@MakotoMiura, do you know the answer to this? Does the SKI electronics have multiple digits per PMT per (sub)event? Does the SKI code in SKDETSIM?

**Comment by cwwalter** [comment]
Can you define exactly what you mean by "multiple digits"?  

If you mean do we know how many times a PMT was hit by photons in the window, I believe the answer is 'no' for all phases  of SK electronics. In SK-IV we have a QTC which records the start of the timing gate and charge for the time you have integrated up over threshold.  In SKI there were effectively 2 ADC/TDCs which switched over after the 1st one was hit to give you "dead timeless" operation.  @MakotoMiura or Hayato (no GH account) should be able to say more.

**Comment by tdealtry** [comment]
To define some terminology:
* hit - a photon (or dark noise) creating a signal on a PMT
* digit - an integration of hits in an integration window by the electronics (with threshold effect). Therefore there is the possibility of multiple hits per digit, and NHits >= NDigits is always true.
* subevent - collection of digits saved around a trigger (e.g. -400 ns to +950 ns around the trigger time)

If you think of the case of a single PMT with 5 hits at 0 ns, and 5 hits at 900 ns (ignoring time and charge smearing):
* single digit per PMT per subevent - Digits saved: 0 ns with 5 p.e. (this is the case in the old WCSim trigger)
* multiple digits per PMT per subevent - Digits saved: 0 ns with 5 p.e., 900 ns with 5 p.e. (this is the case in the new WCSim NDigits trigger)

I'll send an email to Hayato-san, ccing you all.

**Comment by tdealtry** [comment]
After very detailed explanations from Hayato-san regarding how the SKI electronics work, we've decided not to simulate them exactly. But what we do know is:
* a maximum of 1 digit per PMT per trigger window is allowed. I'll make a pull request with this limitation added to the NDigits trigger. As shown above, this will make the NDigits and p.e. distributions agree between the old & new code.
* SKDETSIM seems to use the same algorithms as the new (post #89) code.
* some default WCSim values are not the same as some as-built SKI values. See #112 for more.
