### ISSUE TITLE
Make a separate macro with all the new DAQ options

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#126]
We have lots of new options relating to the DAQ that can be set via the macro. Since vis.mac and novis.mac are getting pretty long, I think we should consider making more specialized macros that show all of the available macro options for a particular topic. We could try this first with the DAQ options.

**Comment by eosullivan** [comment]
Cutting and pasting from the comment section of PR #124, the number of options are: 
/DAQ/Digitizer
/DAQ/Trigger
/DAQ/DigitizerOpt/DeadTime
/DAQ/DigitizerOpt/IntegrationWindow
/DAQ/RestrictDigitsPerTrigger
/DAQ/TriggerSaveFailures/Mode
/DAQ/TriggerSaveFailures/TriggerTime
/DAQ/TriggerSaveFailures/PreTriggerWindow
/DAQ/TriggerSaveFailures/PostTriggerWindow
/DAQ/TriggerNDigits/Threshold
/DAQ/TriggerNDigits/Window
/DAQ/TriggerNDigits/AdjustForNoise
/DAQ/TriggerNDigits/PreTriggerWindow
/DAQ/TriggerNDigits/PostTriggerWindow
/DAQ/Construct

So, perhaps we can keep:
/DAQ/Digitizer
/DAQ/Trigger
/DAQ/Construct

in vis.mac and novis.mac to just show the bare functionality of the DAQ and then include the entire list above in the newly created DAQ macro.

**Comment by tdealtry** [comment]
I think we can close this issue now
