### ISSUE TITLE
Add a geometry identifier to WCSimRootGeom

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#132]
It'll be useful for an identifier of which geometry was used in WCSimRootGeom, so that in output files this information is easily accessible. I see a couple of obvious ways to do this:
- Add a string data member (e.g. the same strings used for /WCSim/WCgeom)
- Add an enumeration of detectors

Let me know what method you prefer and I can add it in. Personally, I prefer the first method, as it's easier to specify different versions of the same geometry (if this is something that happens?), etc.
This is required for hyperk/hk-BONSAI#2

**Comment by eosullivan** [comment]
Adding a string sounds reasonable. Do you have any preference @cvilelasbu? We had talked about adding something like this in to properly interface with fiTQun.

**Comment by tdealtry** [comment]
I've just had a thought - having all the run options (geometry, noise, DAQ, particle gun / input vector file, ...) stored in the output file would be useful. Perhaps we could add a new tree with all this information in?

**Comment by eosullivan** [comment]
Sorry, just rediscovering this now. Does this increase the file size much? Or the time to run the program?

**Comment by eosullivan** [comment]
Also, can I assign you this issue?

**Comment by tdealtry** [comment]
Also just rediscovering this. It'll be a tree with 1 entry, with 20-30 leaves. So it'll be negligible in terms of file size. Running should be quick too - it's just a matter of calling 20-30 `Get*()` methods in `EndOfRunAction()`. Go ahead & assign me, if you think this is a sensible solution.
