### ISSUE TITLE
Solve warning deprecated headers

### ISSUE THREAD

**Issue by tfeusels** [WCSim/WCSim#140]
Many annoying warnings appear during compilation about the deprecated header: #include < ext/hash_map > in WCSimDetectorConstruction.hh.
Compiling with gcc 4.4.7. 
This header should be replaced for a cleaner compilation.
According to backward_warning.h, the replacement header should be: < unordered_map > but the namespace and all hash-related statements need to be updated accordingly as well. The latter can only be used with new C++11 though: -std=c++0x

**Comment by tdealtry** [comment]
Closed via #218
