### ISSUE TITLE
Incorrect detector design in WCSim

### ISSUE THREAD

**Issue by YujiOkajima** [WCSim/WCSim#141]
Current design of cylinder detector for Hyper-Kamiokande in WCSim ("Cylinder_60x74_20inchBandL_14perCent" and "Cylinder_60x74_20inchBandL_40perCent") has inner detector with 74 m diameter and 60 m height. However the candidates of detector design for Hyper-Kamiokande has inner detector with 70.8 m diameter and 54.8 m height.
The whole water tank volume seems to be taken to inner detector volume when the design is 
introduced in WCSim.
Therefore it is necessary to fix the geometry.

**Comment by eosullivan** [comment]
Ok, thanks for bringing this up. Where are you getting these numbers from? Is there a technical drawing somewhere? Are these numbers set or are they still changing?

**Comment by YujiOkajima** [comment]
The diameter and height has been already written in design report (Figure. 35).
So I think this design will not be changed.

**Comment by JostMigenda** [comment]
I changed the dimensions in pull request #151
