### ISSUE TITLE
startup message: No model factories registered

### ISSUE THREAD

**Issue by JostMigenda** [WCSim/WCSim#154]
When running a macro (e.g. `WCSim.mac`), the startup message contains the lines

> Registering model factories...
> G4VisManager: No model factories registered with G4VisManager.
> G4VisManager::RegisterModelFactories() should be overridden in derived
> class. See G4VisExecutive for an example.
> 
> You have successfully registered the following model factories.
> Registered model factories:
>   None

Since this output is produced even with the default macro, I was surprised to find no mention of this in previous issues. Is this intended to be like this (for reasons that are not obvious to me)?

It seems like the WCSimVisManager.cc has something to do with it. I might look at that code later, if I find the time …

**Comment by JostMigenda** [comment]
Huh … while PR #157 removes the warning message, the startup message still says

> Registered model factories:
>   None
>
> Registered models:
>   Unspecified (Current)

In RegisterModelFactories(), a drawByParticleID model is created and RegisterModel(mymodel) is called. So why is that model not registered? Do we need to register a model factory before we can register a model?

**Comment by JostMigenda** [comment]
Apparently, when writing our own visualization manager, we [should refer to](http://www-geant4.kek.jp/lxr/source/visualization/management/src/G4VisManager.cc?v=9.4.p4#L232) the Geant4 source file [G4VisExecutive.icc](http://www-geant4.kek.jp/lxr/source/visualization/management/include/G4VisExecutive.icc?v=9.4.p4#L241) as an example.

After doing so and registering a model factory, the startup message now says:

> You have successfully registered the following model factories.
> Registered model factories:
>   drawByParticleID
>
> Registered models:
>   Unspecified (Current)

which is an improvement. Still, it seems strange to me that no model is registered. Could anyone with more experience take a look at this?

**Comment by eosullivan** [comment]
What is the magnitude of this problem? Is it just that the start up message is not correct/we are using a depreciated way to initialize this model that isn't giving a correct start up message or is this actually affecting the functionality of the code somehow?

**Comment by JostMigenda** [comment]
I originally started looking into this because I couldn’t get the visualizations to work and this seemed like it might be related.
I have since managed to get the OGLSX vis to (mostly) work through other means, though; so as far as I can tell right now, this might just be cleanup work without effects on functionality.
