### ISSUE TITLE
Default dark noise options don't work for non-SK geometries

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#159]
Unless I'm missing something obvious, #101 only works if you don't change from the default geometry (i.e. SK). This is because the dark noise options are read before the geometry is actually constructed.
There's (at least) a couple of ways this could be fixed:
 1. Get the default PMT rate the first time the AddDarkNoise() method is called, only if the messenger hasn't overwritten a (new) unphysical default value.
 1. Create the WCSimWCAddDarkNoise class instance in the same way as the trigger/digitizer options (i.e. in WCSimEventAction::CreateDAQInstances()). Will need to store the DarkNoiseMessenger in the EventAction, and do the (somewhat laborious) job of passing of DarkNoise options from EventAction to AddDarkNoise.

Can someone please confirm the bug? And let me know which solution preference you have? 1 is much simpler to implement, and so is my preference.

**Comment by eosullivan** [comment]
Thanks for pointing this out @tdealtry. I looked back through the verification that was done when this pull request went through, and I don't think this was checked (the checks were done with the default geometry). I'll look into it more when I have a chance, which will hopefully be early next week.

**Comment by thomaslindner** [comment]
Can someone explain: what is the effect of this bug if using non-SK geometry (but if I don't need to change the default PMT rate properties)?  Will everything work with HK geometry + default PMT rate.

**Comment by eosullivan** [comment]
Sorry, I've not had time to look over this bug yet, but if it is true, the dark noise will be set to the 20" PMT value. You can always explicitly specify the dark rate in the macro. For a 20" Box and Line use the lines:

/DarkRate/SetDarkRate 8.4 kHz 
/DarkRate/SetConvert 1.126

**Comment by eosullivan** [comment]
Ok, looking at a couple of simple tests (running WCSim with the 40% HK geometry with the B&L dark rate explicitly set in the macro vs. running the HK geometry and allowing the dark rate to be set automatically) and it looks like the defaults aren't being set correctly. @tdealtry I think option 1 seems sensible. Let's try and get this fixed and then we should probably release a 1.5.1 with this bugfix in it.
