### ISSUE TITLE
ROOT macros not working

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#182]
Since #164, the macros are not working due to the implementations of `G4cout` & `G4cerr` not being found.
There are a few potential fixes
1. Load `${G4LIB}/${G4SYSTEM}/libG4global.so` at runtime
2. Compile `libWCSimRoot.so` using the CLHEP & Geant4 libraries
3. Revert the `G4cerr` to a normal `std::cerr`. This isn't as bad as it first looks - the method that uses `G4cerr` (TriggerType_t WCSimEnumerations::TriggerTypeFromString(std::string s) almost certainly won't be used in the main WCSim code, but only in macros.
4. Add a new file & namespace (e.g. `Utilities.cc`, `Utilities.hh` & `util::`) that contains useful functions for use in macros only (i.e. compiled into `WCSimRoot.so`, but not compiled into the main code). This will prevent `TriggerTypeFromString()` (using `std::cerr` of course) being used by the main code.
5. It's probably possible to pass an `ostream` (e.g. `std::cerr`, `G4cerr`) as an argument to `TriggerTypeFromString()`. Untested.

1 & 2 remove the ability to have a build of WCSim without Geant4, for analysing WCSim output files when you don't have a version of Geant4 installed.
@eosullivan, what's your preferred fix? Personally, I'd go with 4. Let me know & I'll put a pull request in.

**Comment by eosullivan** [comment]
Just to be clear for other users, this bug doesn't affect the WCSim macros (ie. WCSim.mac) but does affect post-WCSim analysis ROOT scripts (the verification test scripts, for example). 

The most reasonable solutions are probably 3 or 4. Solution 3 would just involve reverting #164 and would be the simplest case.  With solution 4 you end up with extra files at the very least, and it might introduce some complication where you have to know there is a separate file with these post-analysis functions where there is a different syntax from the rest of the code. So, my preferred fix is 3.
