### ISSUE TITLE
remove Cylinder_60x74_* configurations

### ISSUE THREAD

**Issue by JostMigenda** [WCSim/WCSim#187]
In #151 we decided to leave these configurations in for the time being. But to reduce clutter and to avoid confusing users, we should remove them in some future release.

(Also: Should we introduce a 14% coverage configuration with the real HK dimensions? We currently have the 60x74 in 40% and 14% configurations, but HK only in the 40% configuration.)

**Comment by tdealtry** [comment]
We have to remember that the 60x74 configurations are what the current fiTQun tunes correspond to, and that they shouldn't be used for the real HK dimensions (see comment by @cvilelasbu in #151)

**Comment by tdealtry** [comment]
These old HK geometries are deprecated in a fatal way since v1.11.0.

They've not been removed fully, due to people *maybe* needing to cross check against old geometries
