### ISSUE TITLE
Stopped muon decay in GEANT 4.9.4

### ISSUE THREAD

**Issue by mscott201** [WCSim/WCSim#189]
Looking at muon neutrino interactions in WCSim as part of the NuPRISM fiTQun validation I noticed that there were a number of events with clear Cherenkov rings that were not associated to any true particle.

Looking in WCSimTrackingAction.cc I found that the true particle trajectories were only saved for "Decay" processes, but that Michel electrons were being produced by both the G4Decay process and the G4MuonMinusCaptureAtRest process.  I've copied some output from the tracking action code below, listing the particle type and its creation process:

track # 2,it is a mu-
track # 49702, it is a e-
    It is from a Decay
track # 49701, it is a anti_nu_e
    It is from a Decay
track # 49700, it is a nu_mu
    It is from a Decay
track # 49699, it is a nu_mu
    It is from a muMinusCaptureAtRest
track # 49698, it is a anti_nu_e
    It is from a muMinusCaptureAtRest
track # 49697, it is a e-
    It is from a muMinusCaptureAtRest

This shows a single muon producing two decay electrons.  Attached is a screenshot of this event, with the muon shown as the solid green line, the electrons as solid blue lines and then the associated neutrinos as the dashed lines.  I was able to display this extra electron by adding `ProcessList.insert("muMinusCaptureAtRest")` to the initialisation of WCSimTrackingAction.cc.
![mu_decay](https://cloud.githubusercontent.com/assets/9436369/19293783/0a9c5c08-8fdc-11e6-83f7-e7007e4e8bd7.png)
Investigating this with Peter Gumplinger, the problem is solved by using GEANT 4.9.6 (or higher).  There were large changes to the muon capture code for v4.9.6 going to the newer version which seems to have fixed this issue.  The second screenshot shows the same event with no changes to WCSim, and the track printout showed electrons coming from the muMinusCaptureAtRest process only (as expected).
![mu_decay_good](https://cloud.githubusercontent.com/assets/9436369/19293878/efb4327a-8fdc-11e6-8ea8-c43c2d71e4b1.png)

If anyone is using decay electrons in their physics studies then they should probably avoid GEANT 4.9.4 I think.  This might also give more impetus for switching the official WCSim GEANT4 version to something more recent.

**Comment by eosullivan** [comment]
Thanks for pointing this out! We are imminently moving to Geant4.10 with PR #178, but this is interesting for people who have been using the current version of the code to note.

**Comment by mscott201** [comment]
Hi Erin - how imminent is the move to Geant 4.10?  We want to start performing analyses using WCSim for the intermediate WC detector and this bug makes it impossible to do so without updating Geant.  

If there is a new release of WCSim with 4.10 in the next week or two then it would make sense for us to wait for that, but if it's not going to be ready until 2017 (say) then we will probably just update to 4.9.6.

**Comment by mscott201** [comment]
Hi Erin - can you give us some information on the schedule to move to Geant 4.10? Thanks!

**Comment by eosullivan** [comment]
Sure. The upgrade had been stalled due to manpower issues, but a new postdoc at QMUL (@sk1806) has recently agreed to look into the remaining issues (mostly related to which secondaries model we should use in Geant4.10). This upgrade is high priority and I would say our aim is to implement these changes in the next month or so. If you do decide to use Geant4.9.6 in the interim, WCSim should work as is, though the outputs haven't been tested very extensively.

**Comment by eosullivan** [comment]
fixed with PR #211
