### ISSUE TITLE
Overlapping triggers with duplicate digits

### ISSUE THREAD

**Issue by cvilelasbu** [WCSim/WCSim#190]
In releases v1.5.0 and later, trigger windows are allowed to overlap and digits in the overlapping interval are saved twice to the output file (once in each trigger).

For example, the following histogram shows the hit times for a muon particle gun event, where hit distributions belonging to different triggers are colour coded and stacked.
![overlappingwcsimtriggers](https://cloud.githubusercontent.com/assets/11177614/19359608/e367abd8-9148-11e6-8813-47edb22ef4a0.png)

In the "old" trigger code (v1.4.0) this didn't happen, as there was a check for previous triggers in the `DigitzeGate` method:

``` c++
G4double lowerbound;
if (G==0) lowerbound = TriggerTimes[G]+EvtG8Down;
  else {
    lowerbound = ( TriggerTimes[G]+EvtG8Down >= TriggerTimes[G-1] + EvtG8Up ) ?  
TriggerTimes[G]+EvtG8Down : TriggerTimes[G-1] + EvtG8Up;
  }
G4double upperbound = TriggerTimes[G]+EvtG8Up;
```

[See here in v1.4.0](https://github.com/WCSim/WCSim/blob/v1.4.0/src/WCSimWCDigitizer.cc#L353:L358)

As far as I can tell, this adjustment for the previous trigger window end time does not exist in the new trigger trigger code's `FillDigitsCollection` method.

``` c++
float lowerbound = triggertime + GetPreTriggerWindow(triggertype);
float upperbound = triggertime + GetPostTriggerWindow(triggertype);
```

[Here in v1.6.0](https://github.com/WCSim/WCSim/blob/v1.6.0/src/WCSimWCTrigger.cc#L319:L320)

Occasionally, `lowerbound` of trigger `N` will be earlier than `upperbound` of trigger `N-1`, so digits between `lowerbound` of trigger `N` and `upperbound` of trigger `N-1` will be saved twice. Is this behaviour intended?

**Comment by tdealtry** [comment]
Hi @cvilelasbu. This is unintended. I'll stick in a PR
