### ISSUE TITLE
comments in NUANCE input file?

### ISSUE THREAD

**Issue by JostMigenda** [WCSim/WCSim#234]
For data management reasons, I think it would be good to have some way to keep track of how (and with what parameters) a NUANCE input file was generated; similar to what Tom implemented for WCSim’s output in #198.

Since the input file is simply a flat text file, its probably easiest to add a few lines that are "commented out" at the start of the text file. As far as I can tell from [documentation](http://neutrino.phy.duke.edu/nuance-format/), though, the NUANCE file format doesn’t have any way of adding comments. Would it be reasonable to add a custom syntax for this?

**Comment by JostMigenda** [comment]
Looking at [the original nuance paper](https://www.sciencedirect.com/science/article/pii/S0920563202017565) and the [Internet Archive version](https://web.archive.org/web/20100612184104/http://nuint.ps.uci.edu/nuance/documentation.htm) of the original documentation web page, it seems pretty clear that there is indeed no comments syntax.

My suggestion would be to interpret lines starting with "#" as comments. (Simply because I’m hoping to use this comment syntax in the supernova event generator [sntools](https://github.com/JostMigenda/sntools), which is written in Python. If there are good arguments for using a different character, that’d be fine with me.)

This would be a simple change to WCSim (ignore lines starting with "#" in [WCSimPrimaryGeneratorAction.cc](https://github.com/WCSim/WCSim/blob/develop/src/WCSimPrimaryGeneratorAction.cc#L95)) and would still allow WCSim to use input files that don’t contain comments.

The only compatibility issue I see is that other software using the NUANCE input format might not be able to read files with such comments. This seems a negligible issue for two reasons, though:
1) I’m not aware of any other software that we’re currently using which relies on this input format.
2) As long as the comments occur only at the beginning of the text file, it would be trivial to delete them manually, where strictly necessary.

**Comment by tdealtry** [comment]
Closed via #277
