### ISSUE TITLE
WCSimRootOptions does not store OD information

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#244]
WCSimRootOptions doesn't store the information of the OD dark noise/digitizer/trigger. WCSimRootOptions therefore needs to be expanded, and the options told to be stored [in WCSimEventAction](../blob/develop/src/WCSimEventAction.cc#L678). This information should be stored in e.g. maps, to allow it to be expanded when there are more than 2 types of PMT.

**Comment by P3tru** [comment]
I missed that, I'll look into it!
