### ISSUE TITLE
NDigits2 Trigger does not handle digit removal properly

### ISSUE THREAD

**Issue by marc1uk** [WCSim/WCSim#245]
The Ndigits2 trigger removes digits from the digits collection in order to avoid duplication when then applying the second level NDigits trigger scan.
However, digit times in the digits collection are stored in a map of digit number vs time. 
When digits are scanned over in WCSimWCTriggerBase::AlgNDigits and WCSimWCTrigger::FillDigitsCollection, digit times are retrieved with a key that is the iteration number of a  simple for loop. This assumes keys follow a monotonic increase from 0 to ndigits. However, when WCSimWCDigi::RemoveDigitizedGate is called it simply erases the digit from the map, breaking this assumption. 

At present the bug goes unnoticed due to the unsafe c-style map addressing in WCSimWCDigi::GetTime (and many others). Replacing this with a safe `map::at` style addressing and placing `try{ } catch (... )` statements around the digit time retrieval demonstrates the problem. (apply the attached patches to `include/WCSimWCDigi.hh` and `src/WCSimWCTrigger.cc`

[trigpatch.txt](https://github.com/WCSim/WCSim/files/2494634/trigpatch.txt)
[digipatch.txt](https://github.com/WCSim/WCSim/files/2494635/digipatch.txt)

**Comment by tdealtry** [comment]
Good spot! Thanks for this.
Could you put a pull request in for a fix for this? I guess it means changing the loops over  in WCSimWCTriggerBase::AlgNDigits() and WCSimWCTriggerBase::FillDigitsCollection():
`for ( G4int ip = 0 ; ip < (*WCDCPMT)[i]->GetTotalPe() ; ip++)`
to loops over the e.g. times map
Swapping from `[]` to `map::at()` in the times & other maps/vectors in WCSimWCDigi would also be a good plan

**Comment by marc1uk** [comment]
Sure, i'm working on a fix and should have something to submit soon.

**Comment by marc1uk** [comment]
Pull requested created: https://github.com/WCSim/WCSim/pull/247
For some reason this link gives me a 404 error, but i can't re-submit the PR because github tells me one is already open. Hopefully it will become visible soon.

**Comment by tdealtry** [comment]
Closed via #247
