### ISSUE TITLE
WCSimRootGeom does not store OD PMTs

### ISSUE THREAD

**Issue by tdealtry** [WCSim/WCSim#250]
Running `testgeo.C` on WCSim output with Hyperk and HyperKWithOD geometries, the output is almost the same:
HyperK
```
Cyl radius 3550.533447
Cyl length 5497.842285
PMT radius 25.400000
Offset x y z 0.000000 0.000000 0.000000
Num PMTs 38448
```
HyperKWithOD
```
Cyl radius 3550.533447
Cyl length 5598.090820
PMT radius 25.400000
Offset x y z 0.000000 0.000000 0.000000
Num PMTs 38448
```
i.e only the Cylinder length is different.

What I think this means is that there is no way to link OD hits/digits to a PMT, therefore there is no way to get hit/digit position for the OD. Please let me know if I'm wrong @P3tru 

I'm not sure what the best way to do this is (i.e. second TClonesArray or just utilise the first one). I think it'll depend on what the tube ids of the OD PMTs are (i.e. whether they run from 0 or N_ID_PMTS).
Of course there are probably a few more OD-related variables to save too.

**Comment by P3tru** [comment]
Hi Tom,

Thanks for noticing, I must have a fix written by Madhi which I had forgotten to merge it seems. I'll fix that now!
