### ISSUE TITLE
Installing WCSim with Root6 and GEANT4-10.* from homebrew

### ISSUE THREAD

**Issue by ghkareem** [WCSim/WCSim#282]
Hi,

Could someone explain how to "try" to load WCSim using homebrew root and GEANT4? brew installs Root6 and geant4-10+; has anyone successfully configured it and if so, could someone guide me through installation? thanks!

**Comment by tdealtry** [comment]
Hi @ghkareem Geant 4.10.1 is the current recommended version, but if you're using 4.10.2 or beyond, reverting #278 might work (it does for 4.10.2, but may not work for the latest version). Note that it is untested, and WCSim has not been tuned to these versions (but some studies have used 4.10.2/3).
I've not tried with root6 - again an older version (5) is the current recommended version. There has been some discussion to move to root6 in HyperK in the nearish future, so if you fancy working out the required changes and putting a PR in, that'd be great and much appreciated!
