### ISSUE TITLE
change version of geant4

### ISSUE THREAD

**Issue by med-ouar** [WCSim/WCSim#316]
hello, 
i was use geant4 10.2.02 and my code work correctly,
now i upgrade to geant4 10.6 and when i run my code i get a lot of errors like this: ( any solution ??!!!)

/home/mohammed/work/proton/include/DetectorMessenger.hh:60:36: warning: private field 'fDetector' is not used [-Wunused-private-field]
    RE03DetectorConstruction*      fDetector;
                                   ^
1 warning generated.
[ 47%] Building CXX object CMakeFiles/RE03.dir/src/PhysicsList.cc.o
/home/mohammed/work/proton/src/EmStandardPhysics.cc:89:3: error: use of undeclared identifier 'aParticleIterator'; did you mean 'GetParticleIterator'?
  aParticleIterator->reset();
  ^~~~~~~~~~~~~~~~~
  GetParticleIterator
/home/mohammed/geant/geant4.10.06.p02-install/include/Geant4/G4VPhysicsConstructor.hh:172:41: note: 'GetParticleIterator' declared here
    G4ParticleTable::G4PTblDicIterator* GetParticleIterator() const;
                                        ^
/home/mohammed/work/proton/src/EmStandardPhysics.cc:89:3: error: reference to non-static member function must be called; did you mean to call it with no arguments?
  aParticleIterator->reset();
  ^~~~~~~~~~~~~~~~~
                   ()
/home/mohammed/work/proton/src/EmStandardPhysics.cc:90:12: error: use of undeclared identifier 'aParticleIterator'
  while( (*aParticleIterator)() ){
           ^
/home/mohammed/work/proton/src/EmStandardPhysics.cc:91:38: error: use of undeclared identifier 'aParticleIterator'
    G4ParticleDefinition* particle = aParticleIterator->value();
                                     ^
/home/mohammed/work/proton/RE03.cc:65:2: error: unknown type name 'G4MTRunManager'; did you mean 'G4RunManager'?
 G4MTRunManager * runManager = new G4MTRunManager;
 ^~~~~~~~~~~~~~
 G4RunManager
/home/mohammed/geant/geant4.10.06.p02-install/include/Geant4/G4RunManager.hh:137:7: note: 'G4RunManager' declared here
class G4RunManager
      ^
/home/mohammed/work/proton/RE03.cc:65:36: error: unknown type name 'G4MTRunManager'; did you mean 'G4RunManager'?
 G4MTRunManager * runManager = new G4MTRunManager;
                                   ^~~~~~~~~~~~~~
                                   G4RunManager
/home/mohammed/geant/geant4.10.06.p02-install/include/Geant4/G4RunManager.hh:137:7: note: 'G4RunManager' declared here
class G4RunManager
      ^
/home/mohammed/work/proton/RE03.cc:66:14: error: no member named 'SetNumberOfThreads' in 'G4RunManager'
 runManager->SetNumberOfThreads(24);
 ~~~~~~~~~~  ^
4 errors generated.
make[2]: *** [CMakeFiles/RE03.dir/build.make:89 : CMakeFiles/RE03.dir/src/EmStandardPhysics.cc.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
[ 52%] Building CXX object CMakeFiles/RE03.dir/src/RE03ActionInitialization.cc.o
3 errors generated.
make[2]: *** [CMakeFiles/RE03.dir/build.make:63 : CMakeFiles/RE03.dir/RE03.cc.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:76 : CMakeFiles/RE03.dir/all] Erreur 2
make: *** [Makefile:130 : all] Erreur 2

**Comment by tdealtry** [comment]
Hi @med-ouar 

Changing Geant4 version changes both the interface that apps need to use (e.g. methods are deprecated then removed - hence your compilation errors) and the physics results. Therefore we need to be careful about incrementing the recommended Geant4 version for use with WCSim - it needs to be well validated. But of course, it is something to do when we have time/manpower

However, I can't see any WCSim files causing errors in your build, therefore I'm assuming that you're not using WCSim, but instead have written your own Geant4 app. Is this correct?
If so, you'll want to get [help from the Geant4 folks](https://geant4.web.cern.ch/support) e.g. via [bugzilla](https://bugzilla-geant4.kek.jp)
If not, then feel free to reopen this issue
