### ISSUE TITLE
Rename WCSimConstructWC to WCSimConstructCylinder

### ISSUE THREAD

**Issue by aihimmel** [WCSim/WCSim#35]
We should make clear that this file is only used to make cylindrical geometries, not all Water Cherenkov detectors.  Since this is only a file name, and not a class name, this should require no change in code other than renaming the file.

**Comment by cwwalter** [comment]
Just for historical information: In case you are interested the reason it is named this way is in the original 2KM code there was a WC detector, a LAR detector and a Muon ranger.  So the name JHF2kmConstructWC meant it was the part of the code for T2K (then named JHF) that made the WC detector part of the 2KM complex.

So changing this to Cylinder (where we already have HyperK) seems fine.

**Comment by aihimmel** [comment]
OK - I'll put this in after the latest pull request gets merged.

**Comment by eosullivan** [comment]
I think all of the pull requests you were waiting on are merged. After you make this fix, we will probably tag out the new release.

**Comment by aihimmel** [comment]
Closed with the last commit.

**Comment by cwwalter** [comment]
BTW: Did you check that there were no issues building this from a clean checkout (I'm wondering about Make and Cmake files that might have references)?  Also, just double checking: there are corresponding .h file and references to it etc right?

**Comment by aihimmel** [comment]
"WCSimConstructWC" doesn't actually show up anywhere.  It is a part of the WCSimDetectorConstruction class and the makefile just figures is out.  (I tried a clean build and had no problems.)  I could also change the name of the function, which would require changing two lines of code, which would also be quite painless.

**Comment by cwwalter** [comment]
Probably changing the function name to match the file is better..

**Comment by aihimmel** [comment]
Again, I checked and it builds from a clean directory.  This one involved changes to the code so I made it a proper pull request.

**Comment by cwwalter** [comment]
This was closed by pull request #40.
