### ISSUE TITLE
Saving trajectory points at ID/OD boundaries

### ISSUE THREAD

**Issue by kmtsui** [WCSim/WCSim#369]
We want to save extra trajectory information for OD study with https://github.com/kmtsui/WCSim/pull/1
It involves some changes to the `WCSimRoot*` classes, not sure if everyone is happy with it.

**Comment by tdealtry** [comment]
Hi @kmtsui Naively I'd say this is fine.
- Most tracks will have 3 empty vectors appended, which I presume (hope) isn't larger than a few bytes. If this assumption is wrong however, doing things differently (e.g. a new container that can link to the `WCSimRootTracks` container via track ID)
- Only one or two tracks from a vertex will have entries, and they're going to be likely <10 elements in these vectors per track. And events that do puncture the ID/OD boundary will have a lot of electron tracks anyway, so this extra info shouldn't be proportionally large

It'd be good if you had some file size numbers to verify this. There's something in `verification-test-scripts/printSizes.C` that _may_ be useful

Also, do you really need `double` precision for positions/energies? Will `float` be adequate?

I also ask at this stage - do you also need time of boundary crossing? This'd be a new `vector<double>` (`double` is important for times)

If you do bring it in, I'd request two additional things
- Example of how to use it in `sample_readfile.C`
- Added as part of the `WCSimRootTrack::CompareAllVariables()` method

And suggest
- The `int` be replaced with an `enum`, defined in `WCSimEnumerations` (along with an `AsString()` function). It's just clearer and easier than having to remember e.g. what "2" means

**Comment by kmtsui** [comment]
Doing the checks one by one now. First is the file size.

For output produced with `verification-test-scripts/electrontest.mac`. The primary electrons basically don't have enough energy to cross the ID boundaries. File size shows negligible increase.
```
Your version of WCSim assumes file: wcsimtest.root
Stable GitHub version of WCSim assumes file: /disk01/usr5/kmtsui/hyperk_repo/WCSim/build/install/wcsimtest.root
The TTree "wcsimGeoT" takes 80682 bytes on disk
  Its branch "wcsimrootgeom" takes 80533 bytes on disk
The branch "wcsimrootgeom" takes 80533 bytes on disk
The TTree "wcsimGeoT" takes 80682 bytes on disk
  Its branch "wcsimrootgeom" takes 80533 bytes on disk
The branch "wcsimrootgeom" takes 80533 bytes on disk
Trees sizes are identical!
The TTree "wcsimT" takes 568130557 bytes on disk
  Its branch "wcsimrootevent" takes 568129825 bytes on disk
  Its branch "wcsimrootevent2" takes 624 bytes on disk
  Its branch "wcsimrootevent_OD" takes 629 bytes on disk
The branch "wcsimrootevent" takes 568129825 bytes on disk
  Its sub-branch "TObject" takes 2486 bytes on disk
  Its sub-branch "fEventList" takes 568127293 bytes on disk
The TTree "wcsimT" takes 567627691 bytes on disk
  Its branch "wcsimrootevent" takes 567626946 bytes on disk
  Its branch "wcsimrootevent2" takes 624 bytes on disk
  Its branch "wcsimrootevent_OD" takes 629 bytes on disk
The branch "wcsimrootevent" takes 567626946 bytes on disk
  Its sub-branch "TObject" takes 2486 bytes on disk
  Its sub-branch "fEventList" takes 567624414 bytes on disk
Your WCSim version tree is 0.0885908% larger than the master GitHub version
The TTree "wcsimRootOptionsT" takes 757 bytes on disk
  Its branch "wcsimrootoptions" takes 604 bytes on disk
The branch "wcsimrootoptions" takes 604 bytes on disk
The TTree "wcsimRootOptionsT" takes 756 bytes on disk
  Its branch "wcsimrootoptions" takes 604 bytes on disk
The branch "wcsimrootoptions" takes 604 bytes on disk
Your WCSim version tree is 0.132275% larger than the master GitHub version
```

Another set of test files with similar macro, but with muon of 5000 MeV to ensure it crosses the ID boundary. Again the file size increase is negligible. 
```
Your version of WCSim assumes file: wcsimmuontest.root
Stable GitHub version of WCSim assumes file: /disk01/usr5/kmtsui/hyperk_repo/WCSim/build/install/wcsimmuontest.root
The TTree "wcsimGeoT" takes 80690 bytes on disk
  Its branch "wcsimrootgeom" takes 80534 bytes on disk
The branch "wcsimrootgeom" takes 80534 bytes on disk
The TTree "wcsimGeoT" takes 80690 bytes on disk
  Its branch "wcsimrootgeom" takes 80534 bytes on disk
The branch "wcsimrootgeom" takes 80534 bytes on disk
Trees sizes are identical!
The TTree "wcsimT" takes 2842905032 bytes on disk
  Its branch "wcsimrootevent" takes 2842904306 bytes on disk
  Its branch "wcsimrootevent2" takes 624 bytes on disk
  Its branch "wcsimrootevent_OD" takes 629 bytes on disk
The branch "wcsimrootevent" takes 2842904306 bytes on disk
  Its sub-branch "TObject" takes 2486 bytes on disk
  Its sub-branch "fEventList" takes 2842901774 bytes on disk
The TTree "wcsimT" takes 2842109300 bytes on disk
  Its branch "wcsimrootevent" takes 2842108579 bytes on disk
  Its branch "wcsimrootevent2" takes 624 bytes on disk
  Its branch "wcsimrootevent_OD" takes 629 bytes on disk
The branch "wcsimrootevent" takes 2842108579 bytes on disk
  Its sub-branch "TObject" takes 2486 bytes on disk
  Its sub-branch "fEventList" takes 2842106045 bytes on disk
Your WCSim version tree is 0.0279979% larger than the master GitHub version
The TTree "wcsimRootOptionsT" takes 765 bytes on disk
  Its branch "wcsimrootoptions" takes 604 bytes on disk
The branch "wcsimrootoptions" takes 604 bytes on disk
The TTree "wcsimRootOptionsT" takes 765 bytes on disk
  Its branch "wcsimrootoptions" takes 604 bytes on disk
The branch "wcsimrootoptions" takes 604 bytes on disk
Trees sizes are identical!
```
I think there should be no problem in file size!

**Comment by tdealtry** [comment]
Great! Happy to merge a PR

**Comment by kmtsui** [comment]
Changes are made based on the suggestions. PR are now in https://github.com/WCSim/WCSim/pull/370
