### ISSUE TITLE
Default value of /DAQ/RelativeHitTime

### ISSUE THREAD

**Issue by kmtsui** [WCSim/WCSim#381]
Should the `RelativeHitTime` variable in `WCSimEventActionn` be given a default `false` value? 
In my local environment, if I don't use the `/DAQ/RelativeHitTime` macro command, the `RelativeHitTime` variable is given a non-zero (true) value. 
Is this behavior expected?

**Comment by tdealtry** [comment]
Yes totally agree that it should be false as default. Please see the PR
