### ISSUE TITLE
Make it possible to digitize info from different PMTs

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#39]
This is needed to simulate the OD for issue #13 and can only be completed after issue #37 and #38. This either requires two separate digitizers that read from the two (ID and OD) types of tubes, or a single digitizer that somehow distinguishes between the ID and OD PMTs. Some thought will have to be put into how to best organize the readout of these digitized collections into the .root file.

**Comment by marc1uk** [comment]
Hi Erin/WCSim members, this is Marcus O'Flaherty, i'm a student working on ANNIE. We're trying to use WCSim to simulate our detector, and would like to include mutliple PMT types, and also include detection from a forward veto and aft muon range detector. I'd like to get involved in helping with this issue. Has any work been done on this to date? Do you have any thoughts for direction to take for implementation, or format of the output files?
Cheers
