### ISSUE TITLE
Bugs with /WCSim/PMTQEMethod Stacking_Only

### ISSUE THREAD

**Issue by kmtsui** [WCSim/WCSim#445]
Maybe this is already known, but when we use `/WCSim/PMTQEMethod Stacking_Only` in detector with OD, the below 400 nm photon QE is boosted by the WLS absorption length, which causes too much ID photons to survive. 

Not sure if any physics study is using such configuration. We just found this bug in IWCD fiTQun tuning.

We may just show a warning in the macro option explaining this issue, or
we can fix it by applying a physical/logical volume check in `WCSimStackingAction::ClassifyNewTrack()` to separate the ID and OD photons.

**Comment by tdealtry** [comment]
We've got [this comment](https://github.com/WCSim/WCSim/blob/develop/WCSim.mac#L151) in the mac file warning (actually not very strongly worded or obvious) that `SensitiveDetector_Only` should be used. This was the result of @spradlin's investigations (e.g. #327) with the consensus from meetings to use `SensitiveDetector_Only` exclusively

But I agree that we can make this clearer. I'm leaning towards hard exitting when not using `SensitiveDetector_Only` I'll put in a PR to do this today

But if you do want to resurrect `Stacking_Only` (or any of the other options) then please do. I would suggest however chatting with @spradlin about it

**Comment by nickwp** [comment]
I also reported in a 2021 software meeting ([here](https://indico-sk.icrr.u-tokyo.ac.jp/event/6546/contributions/19254/attachments/18333/22583/NProuse_HybridWCSimBug.pdf) or [here](https://docs.google.com/presentation/d/1wLhH--LNiQaiAHallEF47oJhI0E24P6zfVdCVAAOj8Q/edit#slide=id.gedf9dd6215_0_0)) that anything other than SensitiveDetector_Only has a bug in the HK Hybrid version with multiple PMT types, which might also affect OD for the same reason, unless it was fixed?
Anyway, I guess this is just another reason not to use anything other than SensitiveDetector_Only.

**Comment by spradlin** [comment]
> I also reported in a 2021 software meeting ([here](https://indico-sk.icrr.u-tokyo.ac.jp/event/6546/contributions/19254/attachments/18333/22583/NProuse_HybridWCSimBug.pdf) or [here](https://docs.google.com/presentation/d/1wLhH--LNiQaiAHallEF47oJhI0E24P6zfVdCVAAOj8Q/edit#slide=id.gedf9dd6215_0_0)) that anything other than SensitiveDetector_Only has a bug in the HK Hybrid version with multiple PMT types, which might also affect OD for the same reason, unless it was fixed? 

I did not fully fix the issues with the QE checks.  As i remember, i thought that a proper solution would involve some reorganization of code.  At the time, the effort required to do so was thought to be better applied to GHOST development.  If it is a necessary feature, i could revisit my notes....

**Comment by kmtsui** [comment]
I don't mean to make large changes to the code. It is good enough to make sure no one is using the option in the wrong way (hybrid or OD configuration).

**Comment by tdealtry** [comment]
Ok great. The hard exit fix will stop people using the bugged options

Thanks for bringing this up @kmtsui
