### ISSUE TITLE
Unfavourable exit from WCSimEnumerations::ProcessTypeStringToEnum()

### ISSUE THREAD

**Issue by kmtsui** [WCSim/WCSim#473]
With the new `WCSimEnumerations::ProcessTypeStringToEnum()`, I do see unknown processes in e.g. pion simulation, which just killed the simulation in a production environment. I don't think it's the best way, if there are so many "unknown" process that we don't know.
```
UNKNOWN PROCESS TYPE: He3Inelastic
You've encountered a new ProcessType_t!Other people will also need to use this, so please put in a pull request,where you add this to WCSimEnumerations (both in the .cc & .hh files)Thank you in advance
````

**Comment by nickwp** [comment]
This is weird:

That process [was included](https://github.com/WCSim/WCSim/pull/469/files#diff-e3421846939d6a7bdac54d32a29e84edcb8654b81bdedf74376cfdd0bad90269R558-R559) but starting with a lowercase `h` where your error message implies it starts with an uppercase `H`.

But the [source code](https://github.com/Geant4/geant4/blob/v10.3.3/source/processes/hadronic/processes/include/G4He3InelasticProcess.hh#L44) for G4.10.3.3 clearly defines the process starting with a lowercase `h`, so I don't know how it's occurring with an uppercase `H` to cause this error.

**Comment by nickwp** [comment]
But in general I think I agree with Ka Ming that for production it feels problematic to cause the program to exit whenever it finds some unknown process, rather than having a safe fallback.

**Comment by tdealtry** [comment]
Yeah agree with both of you. My assumption when I wrote the hard exit was that we'd quickly find all the processes. But there's a lot more rare processes that I thought (and this case issue makes things much more fiddly...)

I'm putting a PR in to remove the hard exist

**Comment by kmtsui** [comment]
Checking all the log, I only found `He3Inelastic` as the unknown process. 
With a search of geant4 source code, I found one possible place of this capitalization:
https://github.com/Geant4/geant4/blob/f77be32f860f3df3984f32f0e8856b7e2af43fb0/source/physics_lists/constructors/ions/src/G4IonPhysics.cc#L147
Hopefully this is the only problematic process name.
