### ISSUE TITLE
Problems Creating BONSAI Tunning File for WCTE

### ISSUE THREAD

**Issue by DiegoCostas97** [WCSim/WCSim#478]
Hello!

I’m trying to create a new BONSAI Tunning File for WCTE and I’m having an issue when running WCSim giving the .kin file that I created following the documentation [here](https://github.com/DiegoCostas97/hk-BONSAI/tree/main/data/tuning):

First I modified `WCSim/sample-root-scripts/MakeKin.py` and added the WCTE geometry:
```
#holds detector [radius, height] in cm
detectors = {"SuperK":[3368.15/2., 3620.],
             "Cylinder_60x74_20inchBandL_14perCent":[7400./2., 6000.],
             "Cylinder_60x74_20inchBandL_40perCent":[7400./2., 6000.],
             "HyperKOld":[7080./2., 5480.],
             "HyperKRealistic":[3242.96 - 200, 6701.41 - 400], #number taken from geofile_HyperK_HybridmPMT_WithOD_Realistic.txt & subtracting 2m FV
             "NuPRISMBeamTest_mPMT":[338.0/2., 369.6]
}
```

And then followed the instructions in the documentation, first, created the .kin file:
`python3.9 /Users/diiego/Desktop/WCSim/sample-root-scripts/MakeKin.py --detector NuPRISMBeamTest_mPMT --direction 4pi --vertex random --energy 10 --type e- --npart 50000`

Then removed DarkNoise and Trigger, and used `/mygen/vecfile eminus_10.0MeV_random_4pi_NuPRISMBeamTest_mPMT_000.kin` in WCTE.mac.

Then I try to run WCSim as usual:
`./bin/WCSim macros/WCTE.mac macros/tuning_parameters.mac`

But this error breaks the simulation:
```
### Run 0 starts.
Set a vector file using the command /mygen/vecfile name
WCSim(18921,0x1f67e2080) malloc: Heap corruption detected, free list is damaged at 0x6000029d3150
*** Incorrect guard value: 7277927384620289620
WCSim(18921,0x1f67e2080) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    18921 abort      ./bin/WCSim macros/WCTE.mac macros/tuning_parameters.mac
```

Thanks!

**Comment by tdealtry** [comment]
Hi @DiegoCostas97 

Have you opened the `.kin` file to check that it doesn't look corrupted?

Can you post the macfile you're using? Just want to check you've set it up as e.g.
```
/mygen/generator muline
/mygen/vecfile eminus_10.0MeV_random_4pi_NuPRISMBeamTest_mPMT_000.kin
```
and that all the other `/mygen/` related options are commented out

**Comment by DiegoCostas97** [comment]
Hi Tom, 

I did not know that the option `/mygen/generator muline` was necessary 🤦‍♂️ 

Now it works, my bad, thanks one more time
