### ISSUE TITLE
Move the PMT threshold cut from WCSimWCDigitizer.cc to WCSimWCPMT.cc

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#48]
This is a bug that was discovered by Debra Dewhurst. The digitizer threshold is implemented before the PMT threshold, which leads to some events in the final digitized collection with less hits than the digitizer threshold. This is an issue only for low energy events. To solve this, the PMT threshold function should be moved into the WCSimWCPMT.cc file (which is probably where it belongs anyways).

**Comment by dewhurst** [comment]
I looked at moving the PMT threshold cut from WCSimWCDigitizer to WCSimWCPMT but as far as I can see this isn't possible at the moment as the information needed for the threshold cut isn't available in WCSimWCPMT. For example, I think information about the gates that's in WCSimWCDigitizer is needed and it's not there at the moment. And also the containers are not the same - WCSimWCPMT deals with hits, whereas WCSimWCDigitiser deals with PMTs hit. So I came to the conclusion that in the way the digitisation is currently done the threshold cut can't be moved to WCSimWCPMT yet. I think this is something that will be easier to do when we look at separating the digitisation and triggers but at the moment isn't really possible. 

I have implemented a possible quick fix in WCSimWCDigitizer.cc where DigitizeGate() makes a check to ensure that after the PMT Threshold is applied the number of hit PMTs > GlobalThreshold (currently 25 hits). This removes the triggers with < 25 hits. However, this won't deal with the fact that some events may have > 25 hits in the entire event window but < 25 hits (after the PMT threshold cut) in the 200ns window that caused the trigger - therefore, if we could go back and say "try to find a trigger again", it might find a different trigger. The only way to get around this is to do:

1. the trigger to be found, 
2. the PMT threshold to be applied,
3. check whether the 200ns window still fulfils the trigger requirements 
4. if it doesn't go back to 1 and repeat.

But again this involves re-writing the digitisation, which is what we're hoping to do in the future but is not going to be quick. So my quick fix does steps 1-3 and removes the ones that no longer fulfil the trigger requirements but then it doesn't do 4 - looking for a new 200ns window with > 25 hits.

That's my current status and so I'm not sure if the quick fix I've done is sufficient/appropriate and whether I should make a pull request? or whether this bug would be better dealt with in the DAQ group separating of the digitisation and triggering? The fix I've made is basically equivalent to asking that all triggers have > 25 hits post WCSim e.g. in general_studies.C, so it may be better to keep it out of WCSim for the moment until a full fix can be implemented.

**Comment by eosullivan** [comment]
Ok, I've just had a look through the code and I see what you mean. This looks more complicated than I initially thought since, as you said below, this threshold has a dependence on the digitizer time window and since the hits are not summed over the PMT in the WCSimWCPMT file.

I've just talked it over with Chris and I think we would prefer to not hard code in that gates with less than 25 hits be discarded. If people who are doing the analysis want to do this quick fix it should be easy for them to put this condition into their analysis code, but if we code it into WCSim it might be hard for new people to know that this problem is in there. We should try and do it right and have it properly implemented in, though it is maybe not immediately clear what that would look like. Do you have access to SKDETSIM? If so, it might be useful to look at how this is implemented there since this code is used for low E analysis and therefore probably has this right.

So, I think it seems like this is not a problem that can be solved this week and so it will probably not be in the next release that we want to put out for the design study. Rather than fix it, it is maybe best to define the problem so that when people use the data set from WCSim they will know it's there. Will you be at the software meeting this week? Could you give a short presentation on this? Miura knows SKDETSIM and SK electronics pretty well and so he might have some good answers to this. Also, could you define the problem for people who might be using this data and for whom this might be an issue? Include how often it happens (for a given energy, I guess) and why it is happening.

**Comment by dewhurst** [comment]
Hi Erin,

Thanks for your response. I agree, I think if we're going to fix the bug we need to do it fully rather than in bits and for the time being the quick fix can be applied in the analysis code post WCSim so I won't make a pull request for the quick fix I made in WCSimWCDigitizer. I do think it will be easier to deal with this once we look at separating out the digitisation and triggering so I will keep it in mind. 

I don't have access to SKDETSIM. Do you know how I can get access? I think that would be extremely useful. I'm happy to put together some slides on this for the software meeting, that's fine.

**Comment by eosullivan** [comment]
Chris told me that there is a version of SKDETSIM which is available to T2K collaborators on a computer at JPARC, though it is a bit of a hassle to get it this way. Could you perhaps ask @fdilodov? She might know where there is a version installed where the UK people could easily get to it. I've had a quick look at it and the threshold part of the code seems to be in dsthr.F, though I guess the more important part is the order in which things are called which may take more digging. Many of the function names are the same in WCSim and SKDETSIM (rn1pe, etc), so grep-ing around might give some answers.

**Comment by tdealtry** [comment]
Now that #89 has been merged, can we close this issue?
From what I understand, the [Threshold()](https://github.com/WCSim/WCSim/blob/develop/include/WCSimWCDigitizerNew.hh#L82) function isn't a threshold on the PMT (the PMT always generates a signal, no matter what input it has) but a threshold on the digitizer (i.e. whether or not the discriminator fires, which is set to ~0.25 p.e.). So having Threshold() in WCSimWCDigitizerSKI (etc.) is the correct place.
