### ISSUE TITLE
PMT cylinder location flag

### ISSUE THREAD

**Issue by gondiaz** [WCSim/WCSim#487]
Knowing the location of each PMT in the detector is important in the fiTQun tuning for the creation of the scattering table and the time pdfs.
There is a flag implemented in WCSim which should specify this information:
https://github.com/WCSim/WCSim/blob/9019993b4fb87645036ae1e67e97080adc10d8e3/include/WCSimRootGeom.hh#L30

But when checking the values for WCTE detector, what you get is the same value (1) for every PMT.

The reason comes from two wrong assumptions in the code that sets this value:
- The central PMT has an mPMT-PMT-id equal to 19 (`nID_PMTs`), but it should be 1
- The cylinder is assumed to be vertically oriented in Z, but WCTE is Y oriented.

https://github.com/WCSim/WCSim/blob/9019993b4fb87645036ae1e67e97080adc10d8e3/src/WCSimConstructGeometryTables.cc#L288

**Comment by kmtsui** [comment]
> The central PMT has an mPMT-PMT-id equal to 19 (nID_PMTs), but it should be 1

The central mPMT ID is 1 in WCTE, but 19 in other detectors.

> The cylinder is assumed to be vertically oriented in Z, but WCTE is Y oriented.

This is true for other nuPrism type detectors.
