### ISSUE TITLE
More precise analysis of HPD parameters

### ISSUE THREAD

**Issue by YujiOkajima** [WCSim/WCSim#82]
The introduced timing resolution of HPD, which was calculated from sigma and lambda of Exponentially modified Gaussian, seems to be different from that timing resolution analyzed from the measurement result in the low charge region. 
I changed the analysis method (make the number of qbin twice as big as past analysis by changing the qbins width, change the fitting target from lambda to 1/lambda) , and analyzed HPD timing resolution again.

1/lambda (new analysis, fitted by 1/(pol1))
![hpd_invert_lambda2](https://cloud.githubusercontent.com/assets/8589041/8082186/4c3d69d8-0fb6-11e5-907e-3eb0d1fe8e39.png)

sigma (new analysis)
![sigma_hpd_test](https://cloud.githubusercontent.com/assets/8589041/8082649/c03ceb76-0fb9-11e5-97ce-f7b094fde642.png)

Timing resolution (sqrt(sigma^2+1/lambda^2), blue: old parameters, red: new parameters)
![hpd_timing_resolution_compare](https://cloud.githubusercontent.com/assets/8589041/8098481/a94885b6-102b-11e5-99d2-c2c1da8696e9.png)

On the other hand, Box and Line PMT seems not to be such a big difference between data and fitted function.
The below figure shows the timing resolution of Box and Line PMT and function which has been introduced in WCSim.
![boxandline_timingresolution](https://cloud.githubusercontent.com/assets/8589041/8082372/c00c60c0-0fb7-11e5-9fc3-d17f432c5f11.png)

**Comment by YujiOkajima** [comment]
As a reference, the timing resolution of Box & Line PMT was analyzed by using the result of 1/lambda fitting.
The figure below shows the relationship between 1/lambda and charge
(Blue: current parameters, Red: new parameters)
![boxandline_timingresolution_newlambda](https://cloud.githubusercontent.com/assets/8589041/8105180/d10a9c9c-1071-11e5-8ccc-d513b827845d.png)

sigma is not changed.

And the figure below shows the timing resolution (Blue: current parameters, Red: new parameters)
![boxandline_newlambdainvert_compare](https://cloud.githubusercontent.com/assets/8589041/8105142/755135e6-1071-11e5-9d9e-1fd056851a97.png)

from this figure, the difference of fitted curve was shown in the middle region of charge.
the difference is less than 0.1 ns but the new timing resolution seems to be better fitted than old version in ~10 ns region.
Therefore I think new parameter is better than current parameters.

**Comment by eosullivan** [comment]
I'm just trying to process how this analysis method has improved the parameters. Why is fitting 1/lambda better than just lambda? And did you make your binning courser or finer? I can't tell from the way you worded it.

**Comment by YujiOkajima** [comment]
I don't understand why the 1/lambda can be fitted better. I fitted 1/lambda because the lambda effect is 
shown in hit time distribution as 1/lambda factor.
When 1/lambda is analyzed instead of direct lambda analysis, the effect of fitting error to timing resolution can be estimated easily.

The bin width of Box & Line PMT was not changed, and the bin width is the same as that of new HPD analysis.
