### ISSUE TITLE
Move dark rate and convert rate from the macro into WCPMTObject

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#84]
This shouldn't have to be set manually by the macro. Since it is a property of the PMt, it should be automatically done when the PD type is changed. This will also need to be done for the OD where the dark rate will be different than the ID.

**Comment by cwwalter** [comment]
We should find out if the dark rate is really just the intrinsic dark rate of the PMT or if it also somehow reflects the radioactive activity in the tank.

**Comment by eosullivan** [comment]
Well, it is currently set differently in the macro for different PD types, so there must be at least some component that is tied to the PD.

**Comment by tfeusels** [comment]
@eosullivan: Is this something that needs help or is are you waiting for proper values for each PD type? SK PMT is 4.2 kHz, 20in B&L seems to converge to 10 kHz. Actually has this been discussed which values will be used as defaults for the reconstruction tuning and physics studies? 

Ideally, we should add the radioactive activity in the tank as separate noise source but I believe this is not even done in skdetsim. Maybe separate issue to open up?

**Comment by eosullivan** [comment]
I intended to do it myself but haven't had any time to even start it, so if you are volunteering I can reassign this to you. Let me know.

My original idea was pretty simple: we are currently changing both the dark rate and the convert rate in the macro depending on which photosensor we are using and I would like it if it automatically changed with the photosensor type to reduce the probability of user error. This could be easily achieved if we move these variables to be a property in WCSimPMTObject. We could also leave in the option to set the value in the macro if someone wanted to increase the dark rate because of their particular configuration. 

The defaults for reconstruction and physics studies are the values in the macros (4.2 kHz, 8.4 kHz, or 3.0 kHz and the corresponding conversion rate depending on the PD type). 

As for the issue of incorporating the radioactivity in the tank, I think it's a further enhancement to what we are doing and therefore a separate issue (though perhaps @cwwalter disagrees).

Also, the dark rate stuff is changing around in pull request #89. I think if it's a small change of setting the default dark rate to be a value in WCSimPMTObject then it would be simple to coordinate with this pull request, though we would need to make sure @tdealtry was happy with it and how it fits in with his new changes.

**Comment by tfeusels** [comment]
I was also thinking of changing it the way you proposed. Simple first: adding it in WCSimPMTObject, while keeping the possibility to change it globally in the macro.

As for the other pull request. Isn't this how the dark rate stuff is used in the electronics, while this is purely how we set it (as property of the PMT)? So I think we keep these separate although it is indeed best to check and coordinate to be sure.

I might get to it today or for sure tomorrow. I'll let you know.

**Comment by eosullivan** [comment]
Ok, great. Thanks for taking this on!

**Comment by tdealtry** [comment]
The new dark noise routine in pull request #89 uses essentially the same algorithm as the old one (in WCSimWCDigitizer) (just adding dark noise to a different time range) & gets the information on dark noise rate & conversion from the WCSimDarkNoiseMessenger (again like the old code). So you can test it on the current code, and easily port it to WCSimWCAddDarkNoise later.
