### ISSUE TITLE
Removing old DUSEL detector configurations

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#91]
In WCSimDetectorConfigs.cc, half of the current configurations are various DUSEL-related detectors. Is anyone using these for anything? I would like to remove them because each time I add a new option that must be specified in the WCSimDetectorConfigs file (a new way of choosing PMTs for example), I must add it to all configurations and then test each one to ensure I haven't introduced an error. With the upcoming addition of an OD to our detectors, perhaps now is the time to delete these defunct options so we only have the options we need/actively use? If anyone desperately wanted to recover the old configurations then they could look through a previous tagged version and fish out the details. Any complaints?

**Comment by cwwalter** [comment]
Yes, please remove the old ones.  They are also one of the reason the .mac files is long and people miss the /construct line.
