### ISSUE TITLE
Add new Hyper-K candidate detector options from July HK Meeting

### ISSUE THREAD

**Issue by eosullivan** [WCSim/WCSim#92]
Add in new candidate options proposed at the Hyper-K meeting as described here: https://wiki.hyperk.org/DesignReport/DetectorOptimization#proposedbasictankperformance

The tanks are both cylindrical with dimensions 60 m (H) x 74 m (D) and both use 20" HQE B&L phototubes. One tank will have a photocoverage of 13.51 % and the other will have a photocoverage of 40 %.

**Comment by tfeusels** [comment]
Unless someone volunteers earlier, I can have a look at it on Wed or earlier... Should be fairly easy and fast and need it anyway asap. Just need to update my local devel version first.

**Comment by eosullivan** [comment]
Ah, I actually just finished doing it. We are trying to push this new release out, so things are a bit more time sensitive than usual. Thanks for the offer!

**Comment by tfeusels** [comment]
Thanks, good to know that it's done.
